CREATE TABLE TCAR_USER_T (
	USER_ID INT NOT NULL AUTO_INCREMENT COMMENT '主键',
	ROLE_ID INT NOT NULL COMMENT 'TCAR_ROLE_T外键',
	USER_NAME VARCHAR(255) NOT NULL COMMENT '用户名',
	PASS_WORD VARCHAR(255) NOT NULL COMMENT '密码',
	USER_PHONE INT NULL COMMENT '手机号',
	SHOW_NAME VARCHAR(100) NULL COMMENT '显示名',
	PRIMARY KEY (`USER_ID`)
)
COMMENT='用户表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_ROLE_T(
	ROLE_ID INT PRIMARY KEY AUTO_INCREMENT comment '主键',
	ROLE_TYPE CHAR(1) NOT NULL COMMENT '1:微信；2:员工；3:管理员',
	ROLE_NAME VARCHAR(255) NOT NULL,
	RIGHT_CODE VARCHAR(500) null 
)
COMMENT='角色表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
create table TCAR_ORDER_T(
	ORDER_ID 				INT PRIMARY KEY AUTO_INCREMENT,
	CREATE_USER_ID 			INT NOT NULL comment 'TCAR_USER_T.USER_ID', 
	CATEGORY_ID 			INT NOT NULL,			 
	GET_CAR_TYPE 			CHAR(1) NOT NULL comment '1:自取；2:送达',
	ESTI_START_DATE			DATE NOT NULL comment '预估开始时间',
	ESTI_END_DATE 			DATE NOT NULL comment '预估结束时间',
	CT_ID					int NOT NULL comment '车型',
	TOTLE_ESTI_AMT 			double(6,2) comment '总预估金额',
	DEPT_ID 				int comment '处理订单的门店，如果=0所有门店都可看到，默认=0',
	ADDR					VARCHAR(500) comment '送车地址',
	PROCESS_USER_ID 		INT comment '订单处理人，由门店得到员工的用户ID',
	ACTUAL_START_DATE 		date comment '实际开始时间',
	CAR_ID					int comment '车牌',
	ACTUAL_END_DATE 		date comment '实际结束时间',
	CREATE_TIME 			TIMESTAMP,
	UPDATE_TIME 			TIMESTAMP,
	ORDER_STATUS 			CHAR(1) comment 'A:待取车;B:待还车;C:取消 F:完成;',
	ATTR1 					VARCHAR(500) comment '取车时照片目录',
	ATTR2 					VARCHAR(500) comment '还车时照片目录'
)
COMMENT='订单表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_CAR_T(
	CAR_ID	INT PRIMARY KEY AUTO_INCREMENT,
	CT_ID INT NOT NULL,
	PLATE_NUMBER VARCHAR(7) comment '车牌'
	
)
COMMENT='汽车表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
create table TCAR_DICTIONARY(
	DICT_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	DICT_TYPE CHAR(1) NOT NULL	comment 'A:级别；'
)
COMMENT='字典表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_CAR_MODELS_T(
	CT_ID    INT PRIMARY KEY AUTO_INCREMENT,
	CT_LEVEL_ID INT comment 'DICT_ID(DICT_TYPE=A)',
	CT_NAME VARCHAR(500),
	CT_IMG_URL VARCHAR(500) comment '车模图片路径',
	CT_DESC VARCHAR(500),
	ESTIMATE_UNIT_PRICE double(6,2)
)
COMMENT='车模表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_EMPLOYEE_T(
	EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID	INT NOT NULL,
	DEPT_ID INT NOT NULL,
	ENABLE_FLAG CHAR(1) NOT NULL comment 'Y:有效；N:无效'
)
COMMENT='员工表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_DEPT_T(
	DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
	DEPL_PHONE INT NOT NULL,
	DEPT_NAME VARCHAR(100) NOT NULL,
	DEPT_ADDR VARCHAR(500) NOT NULL
)
COMMENT='门店表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_AUDIT_T(
	AUDIT_ID int primary key AUTO_INCREMENT,
	AUDIT_TYPE varchar(50) comment 'table Name',
	AUDIT_ACTIVE char(1)	comment '1.新增；2:修改；3:删除'
)
COMMENT='记录表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
CREATE TABLE TCAR_LOG_T(
	LOG_ID int primary key AUTO_INCREMENT,
	ACTIVE_TYPE char(1) comment '1.订单；2.门店；3.员工',
	ACTIVE_USER	int COMMENT '操作员工',
	ACTIVE_TIME TIMESTAMP
)
COMMENT='日志表'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('手动紧凑型','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('经济型','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('商务型','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('豪华型','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('SUV','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('6至15座商务','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('个性车','A');
insert into TCAR_DICTIONARY(NAME,DICT_TYPE) VALUES('电动车','A');


